name: 🐞 Bug report
description: Something isn't working
title: "[BUG] "
labels: ["type: bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: 🐛 Describe the bug
      description: A concise description of what you're experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ✔️ Expected behavior
      description: What's you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 👣 Steps to Reproduce
      description: Steps to reproduce the bug.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 💻 Platform
      description: On which platform did the bug occur?
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: Other
  - type: input
    id: environment
    attributes:
      label: ⭐ Environment
      description: Which is your Andesite version.
      placeholder: "e.g. 1.0.0-SNAPSHOT"
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✍️ Additional context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
