name: 🚀 Feature Request
description: I have a suggestion (and may want to implement it 🙂)!
title: "[FR] "
labels: [ "type: feature" ]
body:
  - type: checkboxes
    attributes:
      label: First, a few things...
      description: This will help us better interpret your request.
      options:
        - label: Is your feature request related to a problem?
          required: false
        - label: Will this feature just help you or is it something everyone needs?
          required: false
        - label: Have you tried to implement or *draft* this feature?
          required: false
        - label: Is your feature a breaking change?
          required: false
  - type: textarea
    attributes:
      label: 😄 Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Add any considered drawbacks.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🧠 Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🤚 Drawbacks
      description: If this feature is a breaking change or what drawbacks does it have?
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 💻 Platform
      description: On which platforms do you want this feature to be applied?
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: Other
  
  - type: input
    id: environment
    attributes:
      label: ⭐ Environment
      description: What is your current Andesite version? Maybe this feature already exists and you don't know
      placeholder: "e.g. 1.0.0-SNAPSHOT"
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✍️ Additional context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
