name: Check source code

on:
  release:
  pull_request:

jobs:
  check:
    name: Check source code with ktlint and detekt
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run `gradlew check`
        run: ./gradlew check
        continue-on-error: false
